apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: amorimdub/udagram-proxy
        name: my-reverseproxy
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
      restartPolicy: Always
